Repository AY2324S2-CS2103-F15-3/tp, pull requests merged in 2024-04, with the labels that each got.

#106 Fixed search command with Checkstyles resolved
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/SearchApplicantCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SearchApplicantCommandParser.java
Labels: priority.High

#116 Update ParserUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.Medium

#123 Add email template button
  src/main/java/seedu/address/ui/EmailWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/EmailWindow.css
  src/main/resources/view/EmailWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#127 Update EmailWindow.java
  src/main/java/seedu/address/ui/EmailWindow.java
Labels: type.Enhancement, priority.Medium

#201 Update UG/DG to address various issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/NoteCommand.java
Labels: priority.High

#204 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow, type.Documentation
